#spring:
#  application:
#    name: qiyu-live-user-provider
#  datasource:
#    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
#    url: jdbc:shardingsphere:classpath:qiyu-db-sharding.yaml
#    hikari:
#      pool-name: qiyu-user-pool
#      minimum-idle: 15
#      idle-timeout: 60000
#      maximum-pool-size: 300
#      connection-timeout: 4000
#      max-lifetime: 60000
#  data:
#    redis:
#      port: 6379
#      host: 172.31.233.237
#      lettuce:
#        pool:
#          min-idle: 10
#          max-active: 50
#          max-idle: 20
## dubbo配置
#dubbo:
#  application:
#    name: ${spring.application.name}
#  registry:
#    address: nacos://192.168.142.128:8848?namespace=c539b406-1e2b-4d4e-a611-d3a28a756871&username=qiyu&password=qiyu
#  protocol:
#    name: dubbo
#    port: 9091
## mq配置
#qiyu:
#  rmq:
#    producer:
#      name-srv: 192.168.142.128:9876
#      group-name: ${spring.application.name}
#      retry-times: 3
#      send-time-out: 3000
#    consumer:
#      name-srv: 192.168.142.128:9876
#      group-name: ${spring.application.name}