spring:
  application:
    name: qiyu-live-id-generate-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.31.233.237:8808/qiyu_live_common?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://192.168.142.128:8848?namespace=c539b406-1e2b-4d4e-a611-d3a28a756871&username=qiyu&password=qiyu
  protocol:
    name: dubbo
    port: 9098