#dubbo:
#  application:
#    name: qiyu-live-api
#    qos-enable: false
#  registry:
#    address: nacos://192.168.142.128:8848?namespace=c539b406-1e2b-4d4e-a611-d3a28a756871&username=qiyu&password=qiyu
#server:
#  servlet:
#    context-path: /live/api